# Generated by Django 3.0.4 on 2020-05-17 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.CharField(max_length=400)),
                ('article', models.TextField()),
                ('video_link', models.URLField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos_article/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos_article/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos_article/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos_article/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos_article/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos_article/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=False)),
                ('article_date', models.DateTimeField(default=datetime.datetime(2020, 5, 17, 17, 23, 56, 58565))),
                ('article_persian_date', django_jalali.db.models.jDateTimeField(default=datetime.datetime(2020, 5, 17, 17, 23, 56, 58565))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='author.Author')),
            ],
        ),
    ]
