# Generated by Django 3.0.4 on 2020-05-17 13:26

import datetime
from django.db import migrations, models
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200517_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='article_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='article_persian_date',
            field=django_jalali.db.models.jDateField(default=jdatetime.datetime.now),
        ),
    ]
