# Generated by Django 3.0.4 on 2020-04-26 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200412_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 20, 47, 45, 380592)),
        ),
    ]
