# Generated by Django 3.0.4 on 2020-05-17 12:53

import datetime
from django.db import migrations, models
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos_author/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 5, 17, 17, 23, 56, 57566))),
                ('start_persian_date', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
            ],
        ),
    ]
