# Generated by Django 3.0.4 on 2020-04-12 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='start_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 12, 21, 59, 41, 978781)),
        ),
    ]
