# Generated by Django 3.0.4 on 2020-05-17 13:21

import datetime
from django.db import migrations, models
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20200517_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='author',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='start_persian_date',
            field=django_jalali.db.models.jDateField(default=jdatetime.datetime.now),
        ),
    ]
