# Generated by Django 3.0.4 on 2020-04-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_location', models.CharField(max_length=100)),
                ('project_alt', models.CharField(max_length=100)),
                ('project_photo', models.ImageField(upload_to='photo_banner/%Y/%m/%d/')),
            ],
        ),
    ]
