# Generated by Django 3.0.4 on 2020-05-17 12:53

import datetime
from django.db import migrations, models
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_location', models.CharField(max_length=100)),
                ('project_alt', models.CharField(max_length=100)),
                ('project_photo', models.ImageField(upload_to='photo_banner/%Y/%m/%d/')),
                ('add_date', models.DateTimeField(default=datetime.datetime(2020, 5, 17, 17, 23, 56, 62561))),
                ('is_published', models.BooleanField(default=True)),
                ('banner_add_date', django_jalali.db.models.jDateTimeField(default=jdatetime.datetime.now)),
            ],
        ),
    ]
