# Generated by Django 3.0.4 on 2020-04-12 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 12, 22, 3, 19, 629409), verbose_name=datetime.datetime(2020, 4, 12, 22, 2, 52, 2936)),
            preserve_default=False,
        ),
    ]
