# Generated by Django 3.0.4 on 2020-05-17 13:08

import datetime
from django.db import migrations, models
import django_jalali.db.models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='time_added',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='banner',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 17, 17, 38, 20, 43708)),
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_add_date',
            field=django_jalali.db.models.jDateField(default=jdatetime.datetime.now),
        ),
    ]
