# Generated by Django 3.0.4 on 2020-05-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20200517_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
