# Generated by Django 3.0.4 on 2020-04-26 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_auto_20200412_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 20, 47, 45, 381590)),
        ),
    ]
